### PR TITLE
Fix/lowercase posts

### PR DESCRIPTION
**Pull request by hlesesne**
On case sensitive systems, Post vs posts seems to break things. The better solution may be to simply move the Posts.js file to _P_osts instead of _p_osts.

### CODE REVIEW

**Comment by pmuens** [comment]
Great! Thank you for the PR! Could you to the same for the comments directory? That would be awesome!

**Comment by hlesesne** [comment]
I'd be glad to, but it doesn't appear that Comments directory has a sister "comments". Or perhaps I am looking in the wrong place?

Would you rather I try to just combine the Posts/posts directory and remove "posts"?

**Comment by hlesesne** [comment]
Actually, looking at the code, you might prefer that I move Comments to comments and Posts to posts and correct the links. I would need to do the same for the containers and components directories to make things consistent.

**Comment by pmuens** [comment]
Yep. That would be great if everything is consistent!

**Comment by hlesesne** [comment]
I completed the directory renaming. Please let me know if there are any problems I missed.

**Comment by pmuens** [comment]
Great! Thank you very much.

**Pull request merged**
